// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0X_K78NpOERoN4p_zP2sV2yzkKs8Y2JM',
    appId: '1:1065690327224:web:60a9f0f38235bc3b18ec4d',
    messagingSenderId: '1065690327224',
    projectId: 'vigor-7e777',
    authDomain: 'vigor-7e777.firebaseapp.com',
    storageBucket: 'vigor-7e777.firebasestorage.app',
    measurementId: 'G-JZXRZ3D14G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRD4FahRJJmPlX_UadowtWMQR1PZpdiv4',
    appId: '1:1065690327224:android:c4d4291084a9b90918ec4d',
    messagingSenderId: '1065690327224',
    projectId: 'vigor-7e777',
    storageBucket: 'vigor-7e777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkR_8M4vbxOPelFiWyOVqdykcLHS6gzZY',
    appId: '1:1065690327224:ios:5f439b0fe663588f18ec4d',
    messagingSenderId: '1065690327224',
    projectId: 'vigor-7e777',
    storageBucket: 'vigor-7e777.firebasestorage.app',
    iosBundleId: 'com.example.vigor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkR_8M4vbxOPelFiWyOVqdykcLHS6gzZY',
    appId: '1:1065690327224:ios:5f439b0fe663588f18ec4d',
    messagingSenderId: '1065690327224',
    projectId: 'vigor-7e777',
    storageBucket: 'vigor-7e777.firebasestorage.app',
    iosBundleId: 'com.example.vigor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0X_K78NpOERoN4p_zP2sV2yzkKs8Y2JM',
    appId: '1:1065690327224:web:bd8224bdcebba61118ec4d',
    messagingSenderId: '1065690327224',
    projectId: 'vigor-7e777',
    authDomain: 'vigor-7e777.firebaseapp.com',
    storageBucket: 'vigor-7e777.firebasestorage.app',
    measurementId: 'G-Y5V9TFPDCX',
  );
}
